// One-off pipeline: rsn-one-html/rsn-one-images/*  ->  public/images/<slot>.webp
// The supplied ".jpg" files are PNGs (~2MB each). We resize to max 1706px (2x the 853px
// artboard) and encode WebP q80. Re-run after dropping new photography into the source folder.
import sharp from 'sharp';
import { readdirSync, mkdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const SRC = fileURLToPath(new URL('../../rsn-one-html/rsn-one-images/', import.meta.url));
const OUT = fileURLToPath(new URL('../public/images/', import.meta.url));
mkdirSync(OUT, { recursive: true });

// Misnamed / duplicate files in the supplied set -> canonical slot name (or null to skip)
const RENAME = {
  'hero-store-footer-01.jp.png': null,          // duplicate of hero-store-footer-01.jpg
  'rop-ceramic-jar-01.jpg': null,               // duplicate of drop-ceramic-jar-01.jpg
  'logo-rsnone-01.jpg': null,                   // PNG (transparent) version is the one we use
  'logo-rsnone-dark-01.jpg': null,
  '42827c48-9827-4ec6-adbc-29e905dd2cb3.png': 'hero-splash-01',
};

let total = 0, count = 0;
for (const f of readdirSync(SRC)) {
  if (!/\.(jpe?g|png)$/i.test(f)) continue;
  let slot = f.replace(/\.(jpe?g|png)$/i, '');
  if (f in RENAME) { if (RENAME[f] === null) continue; slot = RENAME[f]; }
  const isLogo = slot.startsWith('logo-');
  const img = sharp(join(SRC, f));
  const meta = await img.metadata();
  const pipeline = img.resize({ width: Math.min(meta.width ?? 1706, isLogo ? 900 : 1706), withoutEnlargement: true });
  const out = join(OUT, slot + (isLogo ? '.png' : '.webp'));
  if (isLogo) await pipeline.png({ compressionLevel: 9 }).toFile(out);
  else await pipeline.webp({ quality: 80 }).toFile(out);
  const kb = Math.round(statSync(out).size / 1024);
  total += kb; count++;
  console.log(`${slot.padEnd(34)} ${meta.width}x${meta.height} -> ${kb} KB`);
}
console.log(`\n${count} files, ${Math.round(total / 1024 * 10) / 10} MB total`);

// keep src/data/imageIndex.ts in sync so the Img component knows which slots exist
const slots = readdirSync(OUT).filter(f => /\.(webp|png)$/.test(f)).map(f => f.replace(/\.(webp|png)$/, '')).sort();
writeFileSync(fileURLToPath(new URL('../src/data/imageIndex.ts', import.meta.url)),
  '// GENERATED by scripts/convert-images.mjs — do not edit by hand.\nexport const AVAILABLE_SLOTS = new Set<string>([\n' +
  slots.map(s => `  '${s}',`).join('\n') + '\n]);\n');
console.log('src/data/imageIndex.ts updated:', slots.length, 'slots');
